---
- name:                     "cron_localhost: Set Cron Job Facts Block"
  block:
    - set_fact:
        disable_cron_job:    yes
      when:
        - not enable_cron | bool
    - set_fact:
        disable_cron_job:     no
      when:
        - enable_cron | bool
  delegate_to:    localhost
  run_once:       true

- block:
    - name:             "cron_localhost: Make sure Suricata-update/ansible path exists"
      file:
        path:           "{{ suricata_update_path }}/ansible"
        state:          directory
        mode:           '0755'
        owner:          "{{ ansible_user }}"
        group:          "{{ ansible_user }}"

    - name:             "cron_localhost: Make sure Cron Job log path exists"
      file:
        path:           "{{ cron_job_log_path }}"
        state:          directory
        mode:           '0755'
        owner:          "{{ ansible_user }}"
        group:          "{{ ansible_user }}"

    - name:             "cron_localhost: Create Suricata-update cron file"
      template:
        src:            suricata-update-cron.j2
        dest:           "{{ suricata_update_path }}/ansible/corelight-suricata-update-cron-job"
        owner:          "{{ ansible_user }}"
        group:          "{{ ansible_user }}"
        mode:           u=rwx,g=rx,o=rx
  when:
    - enable_cron | bool
  delegate_to:        localhost
  run_once:           true


- name:               "cron_localhost: Ensure Suricata-update runs daily on Suricata-update host"
  cron:
    name:             suricata-update-all
    hour:             "{{ cron_job_hour }}"
    minute:           "{{ cron_job_minute }}"
    cron_file:        suricata-update-cron-job
    job:              "{{ suricata_update_path }}/ansible/corelight-suricata-update-cron-job"
    user:             "{{ ansible_user }}"
    disabled:         "{{ disable_cron_job }}"
    state:            present
  delegate_to:        localhost
  run_once:           true
